version: 1.1 #не трогайте пожалуйста

new-version:
  - '&a[ChatCheck] Вышла новая версия плагина: %version% '
  - '&6Скачать - &a&nspigotmc.org/resources/chatcheck.113569/ '

update-check: true

#слова которые запрещены навашем сервере
bannedmessage:
  - тварь

#наказания которые буду применяться если игрок напишет плохое слово
punishment:
  - kick %player_name% не любим плохие слова

#сообщение в плагине
messages:
  NoPermisionhelp: '&cУ вас нет прав!'
  Reloadplugin: '&aПлагин перезагружен!'
  NoPermisionreload: '&cУ вас нет прав!'
  NoCCcommand: '&cТакой команды нет! &fДоступные команды: &7/cc (help/reload)'
  ProblemUpdateCheker: 'Ошибка при проверки версии плагина!'

# здесь вы можете настроить все права команд
permissions:
  help: 'chatchek.help'
  reload: 'chatcheck.reload'

#сообщение в команда /cc help
help:
  - '&6/cc reload &2- Перезагрузка плагина'
  - '&6/cc help &2- Помощь по плагину'
